pipelines:
    default:
        - step:
            image: luminositylabs/maven:3.5.3-zulu8u172-8.30.01
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
        - step:
            image: luminositylabs/maven:3.5.3-zulu9u07-9.0.7.1
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install
        - step:
            image: luminositylabs/maven:3.5.3-zulu10u01-10.2_11
            script:
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:list-repositories
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging dependency:tree
                - mvn -U -V -s sonatype-settings.xml -Psonatype-snapshots,sonatype-staging clean install