image: maven:3.5.3-jdk-8

pipelines:
    default:
        - step:
            script:
                - mvn -V dependency:list-repositories
                - mvn -V dependency:tree
                - mvn -V clean install
